/* ═══════════════════════════════════════════
   BioBlox - Gender-Specific Bio Lines
   200 Girl | 200 Boy | 200 Neutral
   ═══════════════════════════════════════════ */

const BIO_LINES = {

    // ─── GIRL BIOS (200) ─── Girl-specific emojis: 💅🦋🎀💋💖🌸💕👸🌷💌🛍️💄🩰🌺💗🧚‍♀️
    girl: [
        // Cute / Sweet (30)
        "🌸 soft girl energy activated 🌸",
        "🎀 sugar, spice & everything nice 🎀",
        "💖 born to be a princess, forced to be a boss 💖",
        "🌷 blooming in my own garden 🌷",
        "💕 sweet like strawberry milk 💕",
        "🎀 cute but will steal your heart 🎀",
        "🌸 flower girl in a concrete world 🌸",
        "💗 made of glitter and good vibes 💗",
        "🦋 butterfly kisses and fairy wishes 🦋",
        "💖 soft heart, strong soul 💖",
        "🌸 smells like vanilla and kindness 🌸",
        "🎀 too sweet to be bitter 🎀",
        "💕 cotton candy dreams and starlight 💕",
        "🌷 delicate but never fragile 🌷",
        "💗 sweeter than honey, tougher than you think 💗",
        "🌸 sprinkle kindness like confetti 🌸",
        "🎀 princess energy running through my veins 🎀",
        "💖 soft chapter, main character 💖",
        "🦋 floating through life gracefully 🦋",
        "💕 my heart is made of pastel colors 💕",
        "🌸 gentle soul with a fearless spirit 🌸",
        "🎀 wearing bows and breaking rules 🎀",
        "💗 cute is not a weakness, it's a weapon 💗",
        "🌷 pretty petals, sharp thorns 🌷",
        "💖 the sweetest girl in the lobby 💖",
        "🌸 born with sparkles in my eyes 🌸",
        "🎀 pink isn't just a color, it's a lifestyle 🎀",
        "💕 hugs heal everything 💕",
        "💗 soft girl but i'll protect my friends 💗",
        "🌸 living my cottagecore fantasy 🌸",

        // Baddie / Savage (30)
        "💅 pretty face, savage mind 💅",
        "💋 too glam to give a damn 💋",
        "👸 queen doesn't need a king 👸",
        "💅 nails done, haters blocked 💅",
        "💋 she walks like the world is her runway 💋",
        "👸 crown heavy but she wears it well 👸",
        "💅 unbothered, unstoppable, unforgettable 💅",
        "💋 pretty and petty when needed 💋",
        "👸 bow down or step aside 👸",
        "💅 slay first, slay later, slay always 💅",
        "💋 lips glossed, standards high 💋",
        "👸 ruling this server with grace and chaos 👸",
        "💅 my attitude is as sharp as my eyeliner 💅",
        "💋 sweet smile, savage soul 💋",
        "👸 she conquered what she thought she couldn't 👸",
        "💅 they can watch but they can't compete 💅",
        "💋 dangerous in heels 💋",
        "👸 the queen bee doesn't explain herself 👸",
        "💅 flawless and fearless 💅",
        "💋 she's not a snack, she's the whole buffet 💋",
        "👸 ice cold and diamond bold 👸",
        "💅 born to stand out, not blend in 💅",
        "💋 she shines even in the dark 💋",
        "👸 elegance with an edge 👸",
        "💅 my glow up is permanent 💅",
        "💋 classy with a hint of savage 💋",
        "👸 she turned her pain into power 👸",
        "💅 mirror mirror, i'm the baddest of them all 💅",
        "💋 beauty and the beast? i'm both 💋",
        "👸 queen of my own fairytale 👸",

        // Aesthetic / Dreamy (25)
        "🦋 chasing sunsets and daydreams 🦋",
        "🌸 pastel skies and butterfly eyes 🌸",
        "💌 love letters to the moon 💌",
        "🌷 aesthetic soul, poetic heart 🌷",
        "🦋 dancing with the wind 🦋",
        "🌸 she's a walking Pinterest board 🌸",
        "💌 writing love notes to the universe 💌",
        "🌷 golden hour is my personality 🌷",
        "🦋 soft palette, softer heart 🦋",
        "🌸 living in a watercolor painting 🌸",
        "💌 sealed with a kiss and a dream 💌",
        "🌷 she blooms where she is planted 🌷",
        "🦋 art gallery soul, museum heart 🦋",
        "🌸 lavender haze and rose-tinted days 🌸",
        "💌 pressed flowers and old love songs 💌",
        "🌷 she's poetry in a world of prose 🌷",
        "🦋 twilight girl with starlight dreams 🦋",
        "🌸 soft aesthetic, endless magic 🌸",
        "💌 my diary is full of beautiful chaos 💌",
        "🌷 ethereal and unbothered 🌷",
        "🦋 she carries grace like a garden carries rain 🦋",
        "🌸 velvet voice, silk soul 🌸",
        "💌 vintage vibes and modern dreams 💌",
        "🌷 she's the calm after the storm 🌷",
        "🦋 floating on cloud nine forever 🦋",

        // Preppy / Slay (25)
        "🛍️ shopping is my cardio 🛍️",
        "💄 lip gloss and boss moves 💄",
        "🛍️ she shops therefore she slays 🛍️",
        "💄 outfit check: flawless as always 💄",
        "🛍️ retail therapy is real therapy 🛍️",
        "💄 serve looks, break hearts 💄",
        "🛍️ fashion is my first language 🛍️",
        "💄 she's dressed to impress and express 💄",
        "🌺 trendsetter, not a follower 🌺",
        "💄 pink everything or nothing at all 💄",
        "🛍️ that girl in every room she enters 🛍️",
        "💄 beauty routine is my morning ritual 💄",
        "🌺 she walks in and the room lights up 🌺",
        "💄 gloss on, world off 💄",
        "🛍️ born to slay, dressed to kill 🛍️",
        "💄 confidence is my best accessory 💄",
        "🌺 she's the moment and she knows it 🌺",
        "💄 heels high, standards higher 💄",
        "🛍️ dripping in style, drowning in compliments 🛍️",
        "💄 she ate the look and left zero crumbs 💄",
        "🌺 style icon in the making 🌺",
        "💄 my aesthetic is effortlessly iconic 💄",
        "🛍️ closet full of dreams and fits 🛍️",
        "💄 she doesn't follow trends, she starts them 💄",
        "🌺 polished, poised, powerful 🌺",

        // Flirty / Romantic (25)
        "💌 hopeless romantic with high standards 💌",
        "🌸 she gives butterflies to everyone around 🌸",
        "💕 heart on her sleeve, glitter on her cheeks 💕",
        "💌 love is her superpower 💌",
        "🌸 stealing hearts without even trying 🌸",
        "💕 too cute for one admirer 💕",
        "💌 she flirts with destiny 💌",
        "🌸 blushing is her default mode 🌸",
        "💕 romance novel protagonist energy 💕",
        "💌 catching feelings like catching flowers 💌",
        "🌸 she smiles and the world stops 🌸",
        "💕 sweetheart with a wild side 💕",
        "💌 love at first sight? she IS first sight 💌",
        "🌸 her charm is simply effortless 🌸",
        "💕 fairy tale girl in a modern world 💕",
        "💌 she's the love story everyone wants 💌",
        "🌸 enchanting without even knowing it 🌸",
        "💕 heart eyes and high vibes 💕",
        "💌 the girl they write songs about 💌",
        "🌸 kissed by the moon, loved by the stars 🌸",
        "💕 she makes love look like magic 💕",
        "💌 winking at life and it winks back 💌",
        "🌸 she's the reason for love songs 🌸",
        "💕 pretty in pink and danger in love 💕",
        "💌 she turned heads and broke records 💌",

        // Anime / Kawaii (20)
        "🌸 kawaii queen of the server 🌸",
        "🎀 uwu energy is contagious 🎀",
        "🌸 neko girl vibes activated 🌸",
        "🎀 magical girl transformation complete 🎀",
        "🌸 she's the main girl in an anime world 🌸",
        "🎀 baka but adorable 🎀",
        "🌸 cherry blossom princess 🌸",
        "🎀 shoujo manga protagonist irl 🎀",
        "🌸 senpai noticed her and regretted it 🌸",
        "🎀 she fights evil by moonlight 🎀",
        "🌸 tsundere but make it cute 🌸",
        "🎀 pocky and pixel hearts 🎀",
        "🌸 anime girl with real world charm 🌸",
        "🎀 yandere smile, deredere heart 🎀",
        "🌸 she sparkles like a magical girl 🌸",
        "🎀 idol stage, center position 🎀",
        "🌸 sakura season is her season 🌸",
        "🎀 slice of life heroine 🎀",
        "🌸 she dances like nobody's watching 🌸",
        "🎀 otaku girl with main character aura 🎀",

        // Emo / Dark Girl (20)
        "🖤 dark lace and broken promises 🖤",
        "🥀 she wears her scars like jewelry 🥀",
        "🖤 eyeliner sharp enough to cut 🖤",
        "🥀 roses die but she keeps blooming 🥀",
        "🖤 gothic princess in a pastel world 🖤",
        "🥀 her tears water the flowers 🥀",
        "🖤 dark aesthetic, darker playlist 🖤",
        "🥀 she dances with her demons 🥀",
        "🖤 black dress, black heart, red lipstick 🖤",
        "🥀 tragic beauty, poetic soul 🥀",
        "🖤 moonlight is her spotlight 🖤",
        "🥀 beautiful chaos wrapped in lace 🥀",
        "🖤 she's the villain in her own story 🖤",
        "🥀 wilted rose with thorns of steel 🥀",
        "🖤 melancholy girl with a fierce fire 🖤",
        "🥀 she cries glitter and bleeds stars 🥀",
        "🖤 silent screams, loud fashion 🖤",
        "🥀 broken girl, unbreakable spirit 🥀",
        "🖤 dark side of the moon princess 🖤",
        "🥀 she haunts hearts like a ghost 🥀",

        // Cottagecore / Nature Girl (15)
        "🌸 garden fairy with dirt under her nails 🌸",
        "🦋 she talks to flowers and they listen 🦋",
        "🌸 wildflower girl in a world of concrete 🌸",
        "🦋 barefoot ballerina in the meadow 🦋",
        "🌸 she bakes love into every cookie 🌸",
        "🦋 daisy chains and sunshine reigns 🦋",
        "🌸 tea, honey, and lavender dreams 🌸",
        "🦋 she's a rain girl with a sunshine smile 🦋",
        "🌸 picking strawberries and catching feelings 🌸",
        "🦋 forest fairy with a gentle heart 🦋",
        "🌸 she grew a garden out of her sadness 🌸",
        "🦋 sunrise girl with a moonlit mind 🦋",
        "🌸 spring in her step, autumn in her eyes 🌸",
        "🦋 she hums lullabies to the trees 🦋",
        "🌸 living slow and loving deep 🌸",

        // Y2K / Retro Girl (10)
        "💖 Y2K princess with a flip phone heart 💖",
        "🦋 butterfly clips and frosted lips 🦋",
        "💖 bedazzled everything since birth 💖",
        "🦋 she's giving early 2000s icon vibes 🦋",
        "💖 juicy couture and platform boots 💖",
        "🦋 sparkle girl in a chrome world 🦋",
        "💖 baby pink and baby blue forever 💖",
        "🦋 she's the comeback the 2000s needed 🦋",
        "💖 lowrise queen, high standards 💖",
        "🦋 glitter gel pens and lip smacker dreams 🦋"
    ],

    // ─── BOY BIOS (200) ─── Boy-specific emojis: ⚡🔥💀⚔️🗡️🐺🦅🏆🎮💪🛡️🏎️🥊🎯⚔️
    boy: [
        // Savage / Alpha (30)
        "🔥 built different, wired stronger 🔥",
        "⚔️ king of the lobby, fear the crown ⚔️",
        "💀 no mercy, no retreat, no surrender 💀",
        "🔥 they talk behind my back because they can't face me 🔥",
        "⚔️ warrior by blood, legend by choice ⚔️",
        "💀 fear is for the weak, respect is for the bold 💀",
        "🔥 i don't compete, i dominate 🔥",
        "⚔️ forged in fire, tempered by storms ⚔️",
        "💀 cold-blooded, warm-hearted to the squad 💀",
        "🔥 the only limit is the one i set 🔥",
        "⚔️ conqueror mentality, emperor results ⚔️",
        "💀 they tried to test me, they failed miserably 💀",
        "🔥 built to lead, trained to win 🔥",
        "⚔️ savage mode is my default setting ⚔️",
        "💀 legend in the making, watch the throne 💀",
        "🔥 my hustle speaks louder than their hate 🔥",
        "⚔️ lone wolf, alpha spirit ⚔️",
        "💀 they can copy but never duplicate me 💀",
        "🔥 unbreakable mind, unstoppable grind 🔥",
        "⚔️ king moves only, no pawns here ⚔️",
        "💀 the realest in the room at all times 💀",
        "🔥 too focused to be bothered, too driven to be stopped 🔥",
        "⚔️ respect the crown or feel the blade ⚔️",
        "💀 savage doesn't mean heartless, it means fearless 💀",
        "🔥 i walk different because i think different 🔥",
        "⚔️ blood of a warrior, mind of a strategist ⚔️",
        "💀 silence is my war cry 💀",
        "🔥 they hate the fire because they fear the burn 🔥",
        "⚔️ born to conquer, destined to reign ⚔️",
        "💀 the comeback is always greater than the setback 💀",

        // Gamer / Pro (30)
        "🎮 pro gamer, amateur human 🎮",
        "🏆 GG EZ, next lobby please 🏆",
        "🎮 clutch king, never choke 🎮",
        "🏆 sweaty hands, clean wins 🏆",
        "🎮 controller in hand, crown on head 🎮",
        "🏆 MVP every match, legend every season 🏆",
        "🎮 1v1 me if you dare, bro 🎮",
        "🏆 i don't rage quit, i rage win 🏆",
        "🎮 gaming is not a hobby, it's a calling 🎮",
        "🏆 built different in every lobby 🏆",
        "🎮 respawn and revenge, that's the cycle 🎮",
        "🏆 W after W after W 🏆",
        "🎮 headshot king of the server 🎮",
        "🏆 they call me lag because i'm always ahead 🏆",
        "🎮 cracked at games, stacked in stats 🎮",
        "🏆 carrying this team on my back 🏆",
        "🎮 gaming blood runs through my veins 🎮",
        "🏆 the lobby goes quiet when i join 🏆",
        "🎮 camping is a strategy, not a crime 🎮",
        "🏆 noob slayer, boss player 🏆",
        "🎮 pixel warrior with real skill 🎮",
        "🏆 the scoreboard tells my story 🏆",
        "🎮 AFK in life, active in games 🎮",
        "🏆 clutch or kick? clutch every time 🏆",
        "🎮 speedrunning through these noobs 🎮",
        "🏆 game over? i just started 🏆",
        "🎮 my aim is the only thing that's straight 🎮",
        "🏆 esports mentality, playground vibes 🏆",
        "🎮 they banned my main so i mastered all of them 🎮",
        "🏆 legends never die, they just respawn 🏆",

        // Chill / Cool (25)
        "⚡ too cool to stress, too real to impress ⚡",
        "🔥 chilling like a villain with zero stress 🔥",
        "⚡ easy does it, always ⚡",
        "🔥 laid back but ready to snap when needed 🔥",
        "⚡ cool runs in the family ⚡",
        "🔥 zero drama, hundred percent chill 🔥",
        "⚡ floating through life with no worries ⚡",
        "🔥 the calm before my storm 🔥",
        "⚡ lowkey living, heavyweight winning ⚡",
        "🔥 smooth operator, no stress conductor 🔥",
        "⚡ keeping it a thousand forever ⚡",
        "🔥 too chill for your drama 🔥",
        "⚡ peace is the real flex ⚡",
        "🔥 relaxed but always ready 🔥",
        "⚡ the coolest dude you'll never know ⚡",
        "🔥 ice cold mentality on a hot streak 🔥",
        "⚡ unbothered king of the vibes ⚡",
        "🔥 no tension, just attention 🔥",
        "⚡ smooth moves, smoother mindset ⚡",
        "🔥 living slow but winning fast 🔥",
        "⚡ chill mode: permanently activated ⚡",
        "🔥 not lazy, just strategically relaxed 🔥",
        "⚡ the vibe is immaculate and i'm the source ⚡",
        "🔥 calm under pressure, cool under fire 🔥",
        "⚡ easy breezy, never sleazy ⚡",

        // Funny / Meme (25)
        "💀 i'm not lazy, i'm on energy-saving mode 💀",
        "🔥 professional clown, amateur everything else 🔥",
        "💀 my mom thinks i'm cool, that counts right? 💀",
        "🔥 running on caffeine and bad decisions 🔥",
        "💀 brain.exe has crashed, please stand by 💀",
        "🔥 i put the 'pro' in procrastination 🔥",
        "💀 one braincell and it's napping 💀",
        "🔥 born to be wild, forced to go to school 🔥",
        "💀 my life is a comedy no one asked for 💀",
        "🔥 allergic to mornings, immune to bedtimes 🔥",
        "💀 the class clown grew up but the jokes didn't 💀",
        "🔥 if being confused was a talent i'd be famous 🔥",
        "💀 do i know what i'm doing? no. am i doing it? yes 💀",
        "🔥 NPC behavior with main character confidence 🔥",
        "💀 professionally unserious 💀",
        "🔥 my vibe is 'confused but still winning' 🔥",
        "💀 trust the process (i have no process) 💀",
        "🔥 i'm not lost, i just don't know where i am 🔥",
        "💀 the human version of a shrug emoji 💀",
        "🔥 chaos bro energy since day one 🔥",
        "💀 if sarcasm could kill, i'd be a serial offender 💀",
        "🔥 i tried to be normal, lasted about three seconds 🔥",
        "💀 i came, i saw, i got confused and left 💀",
        "🔥 built different (and not in a good way) 🔥",
        "💀 my plans are more fictional than anime plots 💀",

        // Anime / Weeb (25)
        "⚔️ protagonist of this arc 🗡️",
        "⚡ plus ultra in every battle ⚡",
        "⚔️ unlocked bankai, still can't find the exit 🗡️",
        "⚡ hidden power: still loading ⚡",
        "⚔️ main character with a villain backstory 🗡️",
        "⚡ manga reader, anime watcher, boss fighter ⚡",
        "⚔️ sword boy in a gun world 🗡️",
        "⚡ shonen protagonist energy maximum ⚡",
        "⚔️ tournament arc starts now 🗡️",
        "⚡ power level: over 9000 and climbing ⚡",
        "⚔️ lone samurai, loyal to the code 🗡️",
        "⚡ training arc complete, final boss next ⚡",
        "⚔️ my theme song plays when i enter 🗡️",
        "⚡ the chosen one who chose himself ⚡",
        "⚔️ dark protagonist with a heart of gold 🗡️",
        "⚡ anime villain arc activated 🗡️",
        "⚔️ wielding honor and a sharp blade 🗡️",
        "⚡ silent warrior, loud victories ⚡",
        "⚔️ final form: already unlocked 🗡️",
        "⚡ the plot thickens when i show up ⚡",
        "⚔️ rogue ninja with top-tier skills 🗡️",
        "⚡ filler arc? i skipped it, i'm here for the fight ⚡",
        "⚔️ mech pilot in a fantasy server 🗡️",
        "⚡ every defeat is just a training episode ⚡",
        "⚔️ blade master, heart breaker, floor sweeper 🗡️",

        // Emo / Dark Boy (20)
        "💀 shadow king of the midnight server 💀",
        "🖤 dark soul with a darker playlist 🖤",
        "💀 i walked through fire and forgot to burn 💀",
        "🖤 pain is just weakness leaving the body 🖤",
        "💀 the void stared back and i stared harder 💀",
        "🖤 emo bro but make it legendary 🖤",
        "💀 scars tell stories words never could 💀",
        "🖤 midnight thoughts, daylight battles 🖤",
        "💀 darkness is my comfort zone 💀",
        "🖤 screaming internally, winning externally 🖤",
        "💀 broken chains, free spirit 💀",
        "🖤 too deep for shallow waters 🖤",
        "💀 the wraith nobody sees coming 💀",
        "🖤 black hoodie, blacker coffee, blackest humor 🖤",
        "💀 heartless? no. just selective with my heart 💀",
        "🖤 dead inside but still going hard 🖤",
        "💀 shadows fear what lives in me 💀",
        "🖤 nocturnal king, ruling the darkness 🖤",
        "💀 i didn't choose the emo life, it recognized me 💀",
        "🖤 storm clouds follow me because they respect me 🖤",

        // Grunge / Punk (15)
        "🔥 flannel king, punk soul 🔥",
        "⚡ ripped jeans and rebellion ⚡",
        "🔥 thrift store legend, main stage energy 🔥",
        "⚡ guitars and gasoline mentality ⚡",
        "🔥 90s grunge spirit in a modern world 🔥",
        "⚡ mosh pit general, crowd surf king ⚡",
        "🔥 noise makes more sense than silence 🔥",
        "⚡ skateboard under one arm, attitude in the other ⚡",
        "🔥 punk rock heart with a heavy metal mind 🔥",
        "⚡ rebel without applause ⚡",
        "🔥 distortion is my love language 🔥",
        "⚡ anti-establishment bro since birth ⚡",
        "🔥 diy everything, buy nothing 🔥",
        "⚡ leather jacket weather, always ⚡",
        "🔥 he's the static between radio stations 🔥",

        // Mysterious (10)
        "🐺 lone wolf doesn't need a pack 🐺",
        "🦅 silent predator in a noisy world 🦅",
        "🐺 mystery is my armor, silence is my weapon 🐺",
        "🦅 they wonder about me, i wonder about the universe 🦅",
        "🐺 deep waters, dark currents 🐺",
        "🦅 the eagle flies alone for a reason 🦅",
        "🐺 untamed spirit, unreadable face 🐺",
        "🦅 i speak through actions, never words 🦅",
        "🐺 enigma wrapped in a hoodie 🐺",
        "🦅 watching from the top, unseen and unbothered 🦅",

        // Sports / Athletic (20)
        "🏆 champion mentality from day one 🏆",
        "💪 gym bro energy, no days off 💪",
        "🏆 train hard, dominate harder 🏆",
        "💪 built in the gym, tested on the field 💪",
        "🏆 the grind doesn't stop for holidays 🏆",
        "💪 sweat is just fat crying 💪",
        "🏆 victory is the only option 🏆",
        "💪 iron sharpens iron 💪",
        "🏆 athlete by nature, competitor by choice 🏆",
        "💪 pain is temporary, glory is forever 💪",
        "🏆 second place is the first loser 🏆",
        "💪 discipline over motivation every day 💪",
        "🏆 on the field i become someone else 🏆",
        "💪 no excuses, only results 💪",
        "🏆 born on the court, raised by the game 🏆",
        "💪 stronger than yesterday, weaker than tomorrow 💪",
        "🏆 the scoreboard never lies 🏆",
        "💪 hustle beats talent when talent doesn't hustle 💪",
        "🏆 play hard, rest harder 🏆",
        "💪 my body is a weapon and i keep it loaded 💪"
    ],

    // ─── NEUTRAL BIOS (200) ─── Neutral emojis: ✨⭐🌙☁️🌈🎭🎵🖤🤍💜🌿🎶☀️🌊
    neutral: [
        // Chill / Vibes (30)
        "✨ good vibes only, bad vibes denied ✨",
        "☁️ floating through life, no strings attached ☁️",
        "✨ peace is the ultimate power move ✨",
        "🌙 midnight thoughts with morning energy 🌙",
        "✨ the vibe is immaculate and non-negotiable ✨",
        "☁️ cruising through chaos with calm ☁️",
        "✨ just a chill soul in a hectic world ✨",
        "🌙 stargazer, overthinker, professional dreamer 🌙",
        "✨ my energy is my introduction ✨",
        "☁️ nothing is that serious, breathe ☁️",
        "✨ living proof that peace is powerful ✨",
        "🌙 i flow like water, crash like waves 🌙",
        "✨ serenity is not laziness, it's strategy ✨",
        "☁️ too zen to be stressed, too wise to be pressed ☁️",
        "✨ calm mind, full heart, can't lose ✨",
        "🌙 drifting through life like a falling star 🌙",
        "✨ the universe has my back ✨",
        "☁️ daydreaming is my full-time job ☁️",
        "✨ my aura is chill and you can feel it ✨",
        "🌙 night owl with a golden soul 🌙",
        "✨ stress-free zone, enter at your own peace ✨",
        "☁️ i don't chase, i attract ☁️",
        "✨ lowkey existing, highkey thriving ✨",
        "🌙 moonchild with earth wisdom 🌙",
        "✨ zero drama, maximum karma ✨",
        "☁️ easy breezy, never queasy ☁️",
        "✨ relax, relate, release ✨",
        "🌙 silence is not empty, it's full of answers 🌙",
        "✨ peace before pieces ✨",
        "☁️ soft landing on cloud nine ☁️",

        // Funny / Meme (30)
        "✨ my brain has too many tabs open ✨",
        "⭐ professional overthinker, amateur adult ⭐",
        "✨ i'm not weird, i'm limited edition ✨",
        "⭐ my life is a meme and i'm living for it ⭐",
        "✨ error 404: cool personality not found ✨",
        "⭐ born to lose, too stubborn to accept it ⭐",
        "✨ if sarcasm burned calories i'd be invisible ✨",
        "⭐ certified NPC with main character delusions ⭐",
        "✨ plot twist: i still don't know what i'm doing ✨",
        "⭐ running on vibes and poor decisions ⭐",
        "✨ i peaked at 7 and it's been downhill since ✨",
        "⭐ allergic to alarm clocks ⭐",
        "✨ my therapist has a therapist because of me ✨",
        "⭐ built different (jury's still out on whether that's good) ⭐",
        "✨ professional time waster, amateur everything else ✨",
        "⭐ my attention span left the server ⭐",
        "✨ one braincell hanging on by a thread ✨",
        "⭐ i'm the tutorial NPC nobody listens to ⭐",
        "✨ functioning member of society (citation needed) ✨",
        "⭐ oops i exist ⭐",
        "✨ i was normal once, scariest five minutes of my life ✨",
        "⭐ plan A failed, plan B was never written ⭐",
        "✨ i put the 'fun' in dysfunctional ✨",
        "⭐ WiFi signal stronger than my will to live ⭐",
        "✨ chaos coordinator reporting for duty ✨",
        "⭐ accidentally iconic on purpose ⭐",
        "✨ my autobiography would be filed under comedy ✨",
        "⭐ i make bad decisions at record speed ⭐",
        "✨ napping competitively since birth ✨",
        "⭐ professionally goofy, casually wise ⭐",

        // Aesthetic / Art (25)
        "🌿 art is my oxygen, creativity is my heartbeat 🌿",
        "🤍 minimalist soul in a maximalist world 🤍",
        "🌿 creating beauty from ordinary moments 🌿",
        "🤍 aesthetic is not a trend, it's a lifestyle 🤍",
        "🌿 earth tones and warm hearts 🌿",
        "🤍 old soul, new dreams 🤍",
        "🌿 finding poetry in everything 🌿",
        "🤍 clean lines, clear mind 🤍",
        "🌿 the world is my canvas 🌿",
        "🤍 vintage vibes, timeless soul 🤍",
        "🌿 nature is the greatest artist 🌿",
        "🤍 dark academia energy, light heart 🤍",
        "🌿 painting my life in warm colors 🌿",
        "🤍 journal pages and cafe days 🤍",
        "🌿 living like a studio ghibli film 🌿",
        "🤍 the aesthetic chose me 🤍",
        "🌿 slow mornings, golden evenings 🌿",
        "🤍 curated chaos, organized beauty 🤍",
        "🌿 inhale creativity, exhale masterpieces 🌿",
        "🤍 dreaming in film grain and soft focus 🤍",
        "🌿 simplicity is the ultimate sophistication 🌿",
        "🤍 every day is a new page to design 🤍",
        "🌿 letting the colors tell my story 🌿",
        "🤍 museum heart, gallery mind 🤍",
        "🌿 the quiet beauty of ordinary things 🌿",

        // Mysterious / Deep (25)
        "🌙 some stories are meant to stay untold 🌙",
        "🖤 the less you know, the more interesting i become 🖤",
        "🌙 reading between lines nobody wrote 🌙",
        "🖤 silence is my loudest statement 🖤",
        "🌙 enigma encrypted in a username 🌙",
        "🖤 layers deeper than the ocean floor 🖤",
        "🌙 the answers live in the questions 🌙",
        "🖤 there's a universe behind these eyes 🖤",
        "🌙 walking a path nobody else can see 🌙",
        "🖤 my thoughts are darker than my profile 🖤",
        "🌙 old soul navigating a young world 🌙",
        "🖤 truth hides in plain sight 🖤",
        "🌙 the mystery is the message 🌙",
        "🖤 observing everything, revealing nothing 🖤",
        "🌙 depth over surface, always and forever 🌙",
        "🖤 i am the question mark at the end 🖤",
        "🌙 fog-wrapped soul with clarity within 🌙",
        "🖤 not everyone needs to understand me 🖤",
        "🌙 the night sky knows my secrets 🌙",
        "🖤 my story has chapters you'll never read 🖤",
        "🌙 wandering between worlds nobody sees 🌙",
        "🖤 complex thoughts in a simple bio 🖤",
        "🌙 the shadow has a shadow and it's me 🌙",
        "🖤 born in the in-between 🖤",
        "🌙 i exist in the spaces between words 🌙",

        // Wholesome / Kind (25)
        "🌈 be the reason someone smiles today 🌈",
        "☀️ kindness is free, spread it like sunshine ☀️",
        "🌈 you matter more than you think 🌈",
        "☀️ sending good energy to everyone reading this ☀️",
        "🌈 the world is heavy, be someone's light 🌈",
        "☀️ have you eaten today? drink some water! ☀️",
        "🌈 wholesome energy radiating outward 🌈",
        "☀️ protecting peace, spreading love ☀️",
        "🌈 every soul deserves a warm hello 🌈",
        "☀️ you survived 100% of your worst days ☀️",
        "🌈 cozy vibes and open hearts 🌈",
        "☀️ i'm your biggest fan even if we just met ☀️",
        "🌈 comfort character in real life ☀️",
        "☀️ healing the server one compliment at a time ☀️",
        "🌈 sunshine wrapped in human form 🌈",
        "☀️ blooming at my own pace and that's okay ☀️",
        "🌈 if you need a friend, i'm right here 🌈",
        "☀️ warm hugs and good intentions only ☀️",
        "🌈 the gentlest reminder that you're enough 🌈",
        "☀️ love louder, judge less ☀️",
        "🌈 making the world kinder one rp at a time 🌈",
        "☀️ your vibe attracts your tribe ☀️",
        "🌈 everything will be okay, pinky promise 🌈",
        "☀️ collecting friends, not enemies ☀️",
        "🌈 be the change you need to see 🌈",

        // Music / Creative (20)
        "🎵 living life in 4/4 time 🎵",
        "🎶 my playlist is my personality 🎶",
        "🎵 music is my therapy, rhythm is my pulse 🎵",
        "🎶 headphones in, world out 🎶",
        "🎵 turning feelings into frequencies 🎵",
        "🎶 every moment deserves a soundtrack 🎶",
        "🎵 lost in the melody, found in the beat 🎵",
        "🎶 life without music is just noise 🎶",
        "🎵 singing in the shower, performing in my mind 🎵",
        "🎶 bass drop is my heartbeat 🎶",
        "🎵 creating worlds with sound and silence 🎵",
        "🎶 my ears pick up vibes others can't hear 🎶",
        "🎵 if life had a soundtrack, mine would slap 🎵",
        "🎶 vinyl collector, vibe protector 🎶",
        "🎵 dancing alone in my room is peak happiness 🎵",
        "🎶 the lyrics know me better than i know myself 🎶",
        "🎵 lo-fi beats and midnight feats 🎵",
        "🎶 concert dreams and studio realities 🎶",
        "🎵 my brain plays music that doesn't exist yet 🎵",
        "🎶 tune in, the show is about to start 🎶",

        // Edgy / Deep (20)
        "💜 reality is overrated, imagination is home 💜",
        "🌊 swimming against the current since day one 🌊",
        "💜 society is the real game and nobody read the rules 💜",
        "🌊 the edge is where the view is 🌊",
        "💜 too real for this simulated world 💜",
        "🌊 riding the wave of existence 🌊",
        "💜 consciousness is both the gift and the curse 💜",
        "🌊 deep waters, calm surface 🌊",
        "💜 breaking patterns that no longer serve me 💜",
        "🌊 the universe gave me lore and it's heavy 🌊",
        "💜 normal is an illusion, be extraordinary 💜",
        "🌊 i'm the glitch in the matrix and proud 🌊",
        "💜 born in the wrong timeline but thriving 💜",
        "🌊 questioning everything is my favorite exercise 🌊",
        "💜 my thoughts are deeper than the ocean floor 💜",
        "🌊 comfort zone? i burned it and built a castle 🌊",
        "💜 the abyss waved, i waved back 💜",
        "🌊 existential crisis? nah, existential adventure 🌊",
        "💜 philosophy is my playlist, paradox is my anthem 💜",
        "🌊 deconstructing reality one server at a time 🌊",

        // Nature / Calm (15)
        "🌿 forest soul, river mind 🌿",
        "🌊 ocean heart, mountain spirit 🌊",
        "🌿 the trees are my therapists 🌿",
        "🌊 salt air and sunset prayers 🌊",
        "🌿 grounded like the earth, free like the wind 🌿",
        "🌊 chasing horizons, finding peace 🌊",
        "🌿 wild soul, gentle hands 🌿",
        "🌊 the rain speaks and i listen 🌊",
        "🌿 growing like the roots, reaching like the branches 🌿",
        "🌊 tidal heart, lunar mind 🌊",
        "🌿 the earth heals what the world breaks 🌿",
        "🌊 barefoot on the shore, head in the clouds 🌊",
        "🌿 planted in peace, rooted in love 🌿",
        "🌊 where the river meets the sea, you'll find me 🌊",
        "🌿 breathing in nature, breathing out noise 🌿",

        // Gaming / General (10)
        "✨ main character in every lobby ✨",
        "⭐ respawn, retry, refuse to quit ⭐",
        "✨ level up or log out ✨",
        "⭐ the grind is real and so am i ⭐",
        "✨ pixels and purpose ✨",
        "⭐ just here for the vibes and the dubs ⭐",
        "✨ gaming is my love language ✨",
        "⭐ skill issue? never heard of it ⭐",
        "✨ virtual world, real feelings ✨",
        "⭐ crafting my legacy one round at a time ⭐"
    ]
};
