/* ═══════════════════════════════════════════
 BioBlox - Gender-Specific Bio Lines
 ~394 Girl | ~281 Boy | ~444 Neutral | 100 Garden
 ═══════════════════════════════════════════ */

const BIO_LINES = {

 // ─── GIRL BIOS (~394) ───
 girl: [
"soft girl era and i'm not leaving 🌸",
"sugar rush personality tbh",
"born to be a princess, chose to be a boss 💖",
"blooming at my own pace 🌷",
"sweet like strawberry milk",
"cute but will absolutely rob your heart 🎀",
"flower child in a concrete jungle",
"glitter runs in my veins",
"butterfly kisses and pinky promises 🦋",
"soft heart but strong backbone",
"smells like vanilla and mischief",
"too sweet to be bitter, too real to be fake 🌸",
"cotton candy clouds in my head",
"delicate look, unbreakable spirit 🌷",
"sweeter than honey, tougher than leather",
"princess with a plan 👑",
"soft chapter of a wild story 💖",
"floating through life with a smile 🦋",
"my heart is basically pastel colored",
"gentle soul with a fearless side",
"wearing bows and bending rules 🎀",
"cute is underrated honestly",
"pretty petals, hidden thorns 🌷",
"the sweetest one in the lobby",
"sparkle eyes since day one",
"pink is a whole personality 🎀",
"hugs fix most things tbh",
"soft girl who protects her circle 💗",
"cottagecore heart in a city world 🌸",
"giggles are my default response",
"sunshine mixed with a little hurricane",
"peachy vibes all year round 🍑",
"small but absolutely mighty",
"the sweetest menace you'll meet",
"collecting smiles like they're rare items",
"cherry lip gloss and good intentions 🍒",
"teddy bear energy fr 🧸",
"kind heart, loud laugh",
"marshmallow soul 🤍",
"pretty face, sharp tongue 💅",
"too glam to care 💋",
"queen energy, no crown required 👸",
"nails done, patience gone 💅",
"she walks like the world owes her rent",
"crown heavy but she wears it easy 👸",
"unbothered and unforgettable",
"pretty and petty when the moment calls 💋",
"step aside or get stepped on 👸",
"slay is not a phase, it's a lifestyle 💅",
"lips glossed, standards posted",
"ruling this server with grace and zero apologies 👸",
"my attitude matches my eyeliner: sharp 💅",
"sweet smile, savage brain 💋",
"she conquered what scared her most",
"they watch but can't compete 💅",
"dangerous in heels, deadly in sneakers",
"the queen doesn't need explaining 👸",
"flawless energy only 💅",
"not a snack, the whole menu 💋",
"ice cold and diamond bold",
"born to stand out, allergic to blending in 💅",
"she shines even in the dark 👸",
"elegance with a blade edge",
"my glow up has no off switch 💅",
"classy with a savage chapter 💋",
"turned her pain into a power move 👸",
"mirror mirror, i already know the answer 💅",
"beauty and chaos wrapped in one 💋",
"main character and i'm not sharing the screen 👸",
"not mean, just honest with flair 💅",
"she doesn't chase, she replaces",
"her energy alone is intimidating 💋",
"confidence is louder than words 👸",
"they tried it, she laughed 💅",
"setting the bar and sitting on it",
"she's the plot twist nobody expected 💋",
"too focused to notice the haters",
"they want the recipe but she is the chef 👸",
"walking red flag? nah walking green flag with thorns 🌹",
"chasing sunsets and catching feelings 🦋",
"pastel skies and late nights 🌸",
"love letters written to the moon 💌",
"aesthetic soul, overthinking heart 🌷",
"dancing with the wind 🦋",
"walking Pinterest board honestly 🌸",
"writing notes to the universe 💌",
"golden hour is my whole mood 🌷",
"soft palette, softer heart 🦋",
"living inside a watercolor painting 🌸",
"sealed with a dream and a good playlist 💌",
"she blooms wherever she ends up 🌷",
"art gallery mind, museum quality heart 🦋",
"lavender haze and rose tinted everything 🌸",
"pressed flowers between old book pages 💌",
"poetry in a world of captions 🌷",
"twilight soul with starlight plans 🦋",
"soft aesthetic, endless imagination 🌸",
"my diary reads like a novel 💌",
"ethereal and completely unbothered 🌷",
"grace runs through her like rain 🦋",
"velvet voice, silk intentions 🌸",
"vintage soul, fresh perspective 💌",
"calm after every storm 🌷",
"permanent resident of cloud nine 🦋",
"morning coffee and journal pages ☕",
"sunset collector 🌅",
"fairy lights and midnight talks",
"she's the quiet kind of beautiful 🌙",
"dreaming with her eyes wide open",
"softer than moonlight 🌙",
"made of rainy days and warm tea",
"autumn soul year round 🍂",
"stargazer with a pen and paper 🌟",
"her silence is its own language",
"shopping is my therapy 🛍️",
"lip gloss and power moves 💄",
"she shops, she slays, she repeats 🛍️",
"outfit check: handled 💄",
"retail therapy is valid therapy 🛍️",
"serving looks on a silver platter 💄",
"fashion is my mother tongue 🛍️",
"dressed to impress AND express 💄",
"trendsetter, never a follower 🌺",
"pink everything or we're not going 💄",
"that girl energy in every room 🛍️",
"morning routine is basically an art form 💄",
"she walks in and the room shifts 🌺",
"gloss on, world off 💄",
"born to slay, no off days 🛍️",
"confidence is the best outfit 💄",
"she's the moment, fully aware 🌺",
"heels high, expectations higher 💄",
"dripping in style casually 🛍️",
"ate the look, zero crumbs 💄",
"style icon loading 🌺",
"effortlessly iconic 💄",
"closet full of dreams and fits 🛍️",
"she doesn't follow trends, they follow her 💄",
"polished, poised, probably plotting 🌺",
"it girl arc activated 💅",
"her wardrobe is her autobiography 🛍️",
"she said less is more and still overdressed 💄",
"haute couture heart 🖤",
"accessories louder than words",
"hopeless romantic with standards 💌",
"she gives butterflies without trying 🌸",
"heart on sleeve, glitter on cheeks 💕",
"love is her secret weapon 💌",
"stealing hearts accidentally 🌸",
"too cute for just one admirer 💕",
"flirting with destiny 💌",
"blushing is basically her brand 🌸",
"romance novel main character 💕",
"catching feelings like catching fireflies 💌",
"she smiles and time pauses 🌸",
"sweetheart with a mischievous side 💕",
"love at first profile visit 💌",
"natural charm, zero effort 🌸",
"fairy tale girl, modern world 💕",
"she's the love story everyone rewrites 💌",
"enchanting without a single spell 🌸",
"heart eyes as a permanent state 💕",
"the girl they write playlists about 💌",
"kissed by moonlight 🌙",
"she makes everything look romantic 💕",
"winking at life and it winks back 💌",
"she's why they invented love songs 🌸",
"dangerous combination: pretty and kind 💕",
"head turner, page turner 💌",
"romanticizing her own existence 🌙",
"she fell in love with her own story",
"main love interest vibes 💗",
"old love letters and new beginnings",
"the one they don't get over 💌",
"kawaii mode: always on 🌸",
"contagious uwu energy 🎀",
"neko girl era 🌸",
"magical girl transformation loading 🎀",
"main girl in her own anime 🌸",
"baka but lovable 🎀",
"cherry blossom princess 🌸",
"shoujo protagonist irl 🎀",
"senpai noticed and immediately regretted 🌸",
"fights evil by moonlight 🎀",
"tsundere but cute about it 🌸",
"pocky and pixel hearts 🎀",
"anime girl with irl charm 🌸",
"yandere smile, soft heart 🎀",
"sparkles like a magical girl 🌸",
"center stage idol energy 🎀",
"sakura season incarnate 🌸",
"slice of life heroine vibes 🎀",
"dances like nobody's rendering 🌸",
"otaku girl with protagonist aura 🎀",
"isekai'd into roblox and thriving 🌸",
"her backstory would break the internet 🎀",
"chibi face, full size attitude",
"opening credits playing when she walks in 🎀",
"anime waifu energy honestly 🌸",
"dark lace and sharper promises 🖤",
"she wears her scars like diamonds 🥀",
"eyeliner sharper than words 🖤",
"roses die but she keeps going 🥀",
"gothic princess in everyone else's fairy tale 🖤",
"her tears grow the best flowers 🥀",
"dark aesthetic, darker humor 🖤",
"she dances with her shadows 🥀",
"black dress, red lipstick, zero apologies 🖤",
"tragic beauty, poetic resilience 🥀",
"moonlight is her spotlight 🖤",
"beautiful chaos in lace 🥀",
"she's the villain they secretly root for 🖤",
"wilted rose, steel thorns 🥀",
"melancholy girl with an iron will 🖤",
"cries glitter in private 🥀",
"silent screams, loud fits 🖤",
"broken once, rebuilding forever 🥀",
"dark side of the moon resident 🖤",
"she haunts hearts casually 🥀",
"black coffee soul 🖤",
"she's the midnight nobody stays awake for 🥀",
"velvet darkness and sharp light",
"her playlist is a therapy session 🖤",
"not sad, just aesthetically melancholic 🥀",
"garden fairy with dirty fingernails 🌸",
"talks to flowers, they talk back 🦋",
"wildflower girl in a concrete city 🌸",
"barefoot ballerina in the meadow 🦋",
"bakes love into every cookie 🌸",
"daisy chains and morning rain 🦋",
"tea, honey, lavender, repeat 🌸",
"rain girl with a sunshine laugh 🦋",
"picking strawberries and good vibes 🌸",
"forest fairy, gentle energy 🦋",
"grew a garden from her sadness 🌸",
"sunrise skin, moonlit thoughts 🦋",
"spring steps, autumn eyes 🌸",
"hums lullabies to oak trees 🦋",
"slow living, deep loving 🌸",
"mushroom forager with a poet's heart 🍄",
"she reads in the garden and calls it productivity",
"linen dress, messy hair, perfect day 🌿",
"homemade jam and handwritten letters",
"her happy place smells like soil and rain 🌱",
"Y2K princess with a flip phone heart 💖",
"butterfly clips and frosted lip gloss 🦋",
"bedazzled everything since forever 💖",
"giving early 2000s icon 🦋",
"juicy couture and platform boots 💖",
"sparkle girl in a chrome world 🦋",
"baby pink and baby blue forever 💖",
"the comeback the 2000s deserved 🦋",
"low rise jeans, high standards 💖",
"glitter gel pens and lip smacker dreams 🦋",
"razor flip phone in spirit 📱",
"she listens to 2003 pop unironically 💖",
"jelly sandals and scrunchie queen",
"MSN messenger energy 🦋",
"paris hilton walked so she could run 💖",
"stay gold 🌟",
"chaos with a hair tie",
"she's a whole mood 💅",
"not for everyone and that's the point",
"pretty when she wants to be, terrifying when she needs to be",
"existing loudly",
"she runs on iced coffee and intuition ☕",
"don't confuse her kindness for weakness",
"plot armor is real and she's proof",
"her vibe is invite only 🔒",
"unpredictable in the best way",
"grew up on disney and chose villain energy",
"can't spell legendary without her",
"doing her own thing, loudly",
"she's the storm they weren't ready for ⛈️",
"dont talk to me unless u bring snacks 🍬",
"i know my worth and it aint cheap",
"pretty in person too dw 💅",
"ur fav player ur fav person",
"she believed she could so she did 🎀",
"not ur average girl next door",
"cute but make it dangerous",
"dolled up and dialed in 💄",
"lipgloss and chaos",
"irl i look better trust",
"dont copy my fit ty",
"my style is not for sale 🛍️",
"shes the moment and she knows it",
"born to flex not to stress 💅",
"my vibe my rules",
"angelic face devilish plans",
"you wish you were this pretty fr",
"runway model trapped in roblox",
"doing my nails while winning",
"mirror says im the fairest 👑",
"rainy day person in a sunny world 🌧️",
"tea and cookies typa girl",
"fairy lights and late night talks 🌙",
"reading books in my roblox mansion",
"stargazing from my bloxburg roof",
"lavender dreams 💜",
"messy bun gang",
"oversized hoodie collector",
"painting my feelings away 🎨",
"poetry girl but cooler",
"journaling my roblox adventures",
"daydreaming about my next outfit",
"candles lit mood set",
"cloud watching enthusiast ☁️",
"the quiet girl with the coolest house",
"90s baby aesthetic 📼",
"old soul young face",
"im the main character of my diary",
"soft girl but with opinions",
"doodling on everything",
"will trade everything for pets 🐾",
"dancing in the lobby alone",
"my avatar is cuter than me and im ok w that",
"adopt me girly forever 🥚",
"collecting limited items since 2020",
"spinning in circles rn",
"if u see me afk im eating",
"my inventory is my personality",
"mall rp queen fr fr",
"spent all my robux no regrets 💸",
"im the girl who says gg even when i lose",
"bloxburg interior designer wannabe",
"hair color changes daily",
"my closet is my flex",
"matching fit with my bestie rn 👯",
"school rp tryhard ngl",
"the friend who decorates everything",
"window shopping in the catalog",
"my avatar eats yours sorry",
"will do anything for a golden pet",
"dont ask why im online at 3am",
"living for the weekends tbh",
"homework later roblox now",
"i have trust issues with traders",
"blocking ppl is self care",
"tired but still logging in",
"my mom said 10 more minutes an hour ago",
"i need more friends on here fr",
"online school dropout roblox graduate",
"i talk a lot sorry in advance",
"my screen time is embarrassing dw about it",
"been through 12 friend groups this year",
"i dont do drama unless its rp drama",
"my sleep schedule is nonexistent 😴",
"running from responsibilities into roblox",
"i judge ppl by their avatar ngl",
"wifi is the love of my life",
"my real personality unlocks after midnight",
"2 phones 1 for roblox 1 for everything else",
"if this game crashes im crying",
"shes cool 🧊",
"pink everything",
"soft but psycho",
"taken by roblox",
"ur loss not mine",
"level 9000 bestie",
"flowers in my hair 🌺",
"drama free zone",
"built this avatar from scratch",
"dont test me 💗",
"she/her btw",
"queen behavior only",
"the it girl era",
"im lowkey addicted",
"smile more worry less",
"blonde era 🫶",
"cats > everything",
"pink clouds and loud music",
"bestie come play w me",
"im literally just a girl",
"unbothered is my default setting",
"they stare because they wish",
"cold hands warm fits",
"designer on a roblox budget",
"expensive taste free game",
"walk in like i own the server",
"iced out avatar irl im in pjs",
"attitude problem and proud of it 💅",
"classy until provoked",
"silence is my loudest flex",
"she walks like she owns the place bc she does",
"villain origin story loading",
"making haters uncomfortable since day one",
"too busy being iconic sorry",
"red flag collector but make it cute 🚩",
"not mean just honest",
"my existence is the flex",
"pretty and slightly unhinged",
"idgaf era permanently",
"the baddest in the building 🏢",
 ],

 // ─── BOY BIOS (~281) ───
 boy: [
"built different, wired different 🔥",
"king of the lobby, earn the crown or leave ⚔️",
"no mercy, no excuses 💀",
"they talk behind my back because they can't keep up 🔥",
"warrior mindset since birth ⚔️",
"fear is optional, respect isn't 💀",
"i don't compete, i set the pace 🔥",
"forged in fire, cooled in ice ⚔️",
"cold blooded but loyal to the squad 💀",
"the ceiling is wherever i say it is 🔥",
"conqueror mentality, no shortcuts ⚔️",
"they tested me and got graded 💀",
"built to lead, stays in front 🔥",
"savage mode is the default ⚔️",
"legend in progress, watch the arc 💀",
"hustle speaks, hate whispers 🔥",
"lone wolf energy, pack leader results ⚔️",
"copies don't sell like originals 💀",
"king moves only ⚔️",
"realest in the room, any room 💀",
"too locked in to be distracted 🔥",
"respect the grind or move ⚔️",
"fearless is just another tuesday 💀",
"walk different because i think different 🔥",
"strategist brain, warrior hands ⚔️",
"silence is my loudest flex 💀",
"they hate the flame because it's too close 🔥",
"born to conquer, decided to reign ⚔️",
"comebacks are my cardio 💀",
"actions loud enough to skip the intro",
"calm face, chaotic plans 🔥",
"zero tolerance for weakness ⚔️",
"hard to read, harder to beat",
"the throne was empty so i sat down 👑",
"not cocky, just correct 🔥",
"they made a wall, i made a door ⚔️",
"ice in my veins, fire in my goals",
"carrying the name, not dropping it 💀",
"pro gamer, part time human 🎮",
"GG EZ, next lobby 🏆",
"clutch king, never fold 🎮",
"sweaty hands, clean record 🏆",
"controller in hand, crown on head 🎮",
"MVP every match no debate 🏆",
"1v1 me if you want the humbling 🎮",
"i rage win, not rage quit 🏆",
"gaming isn't a hobby it's heritage 🎮",
"different breed in every lobby 🏆",
"respawn and revenge cycle 🎮",
"W collector 🏆",
"headshot specialist 🎮",
"they call me lag because i'm ahead of everyone 🏆",
"cracked at games, stacked in stats 🎮",
"carrying this squad on my back 🏆",
"gaming runs in the bloodline 🎮",
"the lobby goes quiet when i connect 🏆",
"camping is a valid strategy fight me 🎮",
"noob slayer on the clock 🏆",
"pixel warrior with real hands 🎮",
"scoreboard is my autobiography 🏆",
"AFK in life, online where it counts 🎮",
"clutch every time, no discussion 🏆",
"speedrunning through the competition 🎮",
"game over? i just loaded in 🏆",
"my aim doesn't miss and neither do i 🎮",
"esports brain, playground mouth 🏆",
"banned my main so i learned them all 🎮",
"legends respawn, noobs spectate 🏆",
"ranked grind never stops 🎮",
"keyboard warrior and proud of it",
"win streak longer than my homework 🏆",
"they nerfed everyone else and i still win 🎮",
"gaming chair carrying more than my team",
"if there's a leaderboard i'm on it 🏆",
"L collector? nah i return those 🎮",
"built my whole personality around W's",
"loading screen is the only break i take 🎮",
"they spectate because they can't compete 🏆",
"too cool to stress, too real to impress ⚡",
"chilling like a villain with zero drama 🔥",
"easy does it, always ⚡",
"laid back but ready when needed 🔥",
"cool runs in the family ⚡",
"zero drama, full chill 🔥",
"floating through life unbothered ⚡",
"the calm before the clutch 🔥",
"lowkey living, heavyweight winning ⚡",
"smooth operator mode 🔥",
"keeping it solid forever ⚡",
"too chill for your chaos 🔥",
"peace is the real W ⚡",
"relaxed but never lacking 🔥",
"coolest dude you won't notice ⚡",
"ice cold mind on a hot streak 🔥",
"unbothered king ⚡",
"no tension, just presence 🔥",
"smooth moves, smoother mindset ⚡",
"living slow, winning fast 🔥",
"chill mode: permanent ⚡",
"not lazy, strategically relaxed 🔥",
"vibe source, not vibe leech ⚡",
"calm under pressure, cool under fire 🔥",
"easy breezy, zero sleazy ⚡",
"too peaceful to be bothered",
"headphones in, problems out 🎧",
"the quiet one who wins loud",
"vibing is a full time commitment ⚡",
"nah i'm good, thanks 🔥",
"he speaks softly but his stats don't 🏆",
"my resting face is my brand",
"zero urgency, still on time ⚡",
"cool enough to not need to prove it",
"the definition of minding my own business 🔥",
"not lazy, energy saving mode 💀",
"professional clown, amateur at life 🔥",
"my mom thinks i'm cool and that's enough 💀",
"running on caffeine and chaos 🔥",
"brain.exe has stopped responding 💀",
"i put the 'pro' in probably not 🔥",
"one braincell and it's on vacation 💀",
"born to be wild, forced to attend school 🔥",
"my life is a sitcom with no laugh track 💀",
"allergic to mornings, addicted to staying up 🔥",
"class clown who graduated to server clown 💀",
"confused is my comfort zone 🔥",
"do i know what i'm doing? absolutely not. am i doing it? absolutely yes 💀",
"NPC behavior with main character confidence 🔥",
"professionally unserious since birth 💀",
"confused but winning somehow 🔥",
"trust the process (there is no process) 💀",
"not lost, just exploring aggressively 🔥",
"human shrug emoji 💀",
"chaos bro energy 🔥",
"tried being normal, lasted about four seconds 💀",
"came, saw, got confused, left 🔥",
"built different and my doctor agrees 💀",
"my plans are more fictional than my avatar 🔥",
"homework says it's due tomorrow, i say that's future me's problem 💀",
"functioning human (allegedly)",
"if overthinking was a sport i'd have gold medals 🔥",
"the audacity is free and i'm stocked up 💀",
"google maps can't even find my motivation",
"i'm that friend your mom warned you about (she was right) 💀",
"my autobiography would be in the comedy section 🔥",
"accidentally funny on purpose",
"i peaked at recess and i've accepted it 💀",
"doing the bare minimum with maximum confidence 🔥",
"giving side character energy and i'm fine with it",
"i'm the comic relief nobody asked for 💀",
"born confused, currently thriving 🔥",
"my wifi is more stable than my life plans",
"procrastination speedrunner, world record holder 💀",
"the only thing consistent about me is my inconsistency 🔥",
"protagonist of this arc ⚔️",
"plus ultra, every fight ⚡",
"unlocked bankai, still lost 🗡️",
"hidden power loading ⚡",
"main character with a villain origin story ⚔️",
"manga reader, boss fighter ⚡",
"sword guy in a gun lobby 🗡️",
"shonen energy at max ⚡",
"tournament arc starts now ⚔️",
"power level: still climbing ⚡",
"lone samurai, loyal to the code 🗡️",
"training arc done, boss fight next ⚡",
"theme song plays when i enter ⚔️",
"the chosen one who chose himself ⚡",
"dark protagonist, gold heart 🗡️",
"villain arc loading ⚡",
"wielding honor and a sharp blade ⚔️",
"silent warrior, loud results ⚡",
"final form: already here 🗡️",
"the plot thickens when i show up ⚡",
"rogue ninja with cracked skills ⚔️",
"skipped the filler, here for the fight ⚡",
"mech pilot in a fantasy server 🗡️",
"every L is a training episode ⚡",
"blade master, floor sweeper ⚔️",
"anime villain laugh when i win 🗡️",
"my backstory is too long for this bio ⚡",
"awakened my cursed technique ⚔️",
"side character? nah, narrator 🗡️",
"the power of friendship except i solo'd it ⚡",
"domain expansion: this entire lobby ⚔️",
"gear fifth unlocked casually 🗡️",
"he's the final boss and the checkpoint ⚡",
"my theme song hits different at 2am",
"talk no jutsu doesn't work on me ⚔️",
"shadow king of the midnight lobby 💀",
"dark soul, darker playlist 🖤",
"walked through fire, forgot to flinch 💀",
"pain exits, strength enters 🖤",
"the void stared, i stared harder 💀",
"emo era but make it legendary 🖤",
"scars tell better stories 💀",
"midnight thoughts, daylight battles 🖤",
"darkness is comfortable at this point 💀",
"screaming inside, winning outside 🖤",
"broken chains, free hands 💀",
"too deep for shallow people 🖤",
"the wraith nobody saw coming 💀",
"black hoodie, blacker coffee, darker humor 🖤",
"selective with my heart, not heartless 💀",
"dead inside but still going hard 🖤",
"shadows respect what lives in me 💀",
"nocturnal king, ruling the dark 🖤",
"emo life recognized me first 💀",
"storm clouds follow by choice 🖤",
"he smiles and it means nothing good 💀",
"comfort zone is the abyss 🖤",
"3am thoughts as a personality",
"the darkness is warm actually 💀",
"his playlist could make you cry 🖤",
"flannel king, punk everything 🔥",
"ripped jeans, ripped expectations ⚡",
"thrift store legend 🔥",
"guitars and gasoline ⚡",
"90s grunge in a modern frame 🔥",
"mosh pit veteran ⚡",
"noise is better than silence 🔥",
"skateboard and attitude package deal ⚡",
"punk heart, metal mind 🔥",
"rebel without a script ⚡",
"distortion is love 🔥",
"anti-mainstream since birth ⚡",
"DIY everything 🔥",
"leather jacket weather every day ⚡",
"he's the static between stations 🔥",
"band tee collector with good taste ⚡",
"garage band energy in a digital world 🔥",
"stage dived into roblox",
"vans, chains, and no explanations ⚡",
"his aesthetic is loud 🔥",
"lone wolf, no pack needed 🐺",
"silent predator in a noisy lobby 🦅",
"mystery armor, silence weapon 🐺",
"they wonder, i don't explain 🦅",
"deep waters run dark 🐺",
"the eagle flies alone, there's a reason 🦅",
"untamed and unreadable 🐺",
"actions speak, words stay home 🦅",
"enigma in a hoodie 🐺",
"watching from the top, unseen 🦅",
"you'll know me when you need to 🐺",
"less you know the better",
"quiet mouth, loud presence 🦅",
"his silence says more than their speeches 🐺",
"the unknown player with the known stats 🦅",
"gym bro, zero rest days 💪",
"train hard, win harder 🏆",
"built in the gym, tested on the field 💪",
"grind doesn't stop for weekends 🏆",
"sweat is earned not complained about 💪",
"iron sharpens iron 💪",
"athlete by nature, competitor by default 🏆",
"second place is first loser 🏆",
"different person on the field 🏆",
"no excuses, only reps 💪",
"born on the court, raised by the game 🏆",
"scoreboard is honest 🏆",
"talent sleeps, hustle doesn't 💪",
"play hard, recover harder 🏆",
"early mornings built this 🏆",
"sweat now, flex later",
"record breaker in training 💪",
"the field is where excuses go to die 🏆",
"stay solid 🔥",
"chaos with a game plan",
"he's a whole different breed",
"not for everyone and works for me",
"underestimate me, that'll be fun",
"existing on hard mode",
"runs on black coffee and spite ☕",
"don't mistake quiet for soft",
"plot armor thick 🛡️",
"private life, public wins 🔒",
"unpredictable and unbothered",
"grew up on anime and chose the villain arc",
"can't spell legend without me",
"doing my own thing, always",
"he's the storm they should've tracked ⛈️",
 ],

 // ─── NEUTRAL BIOS (~444) ───
 neutral: [
"floating through the day, no strings ☁️",
"midnight brain, morning energy 🌙",
"cruising through chaos calmly ☁️",
"stargazer and professional overthinker 🌙",
"none of this is that serious, breathe ☁️",
"flow like water, crash when needed 🌙",
"too zen to stress, too wise to press ☁️",
"drifting like a falling star 🌙",
"daydreaming professionally ☁️",
"night owl with a golden core 🌙",
"i don't chase vibes, i set them ☁️",
"lowkey existing, highkey living",
"moonchild energy 🌙",
"easy going, hard to rattle ☁️",
"silence answers louder than shouting 🌙",
"cloud nine resident ☁️",
"napping with intention",
"slow mornings are underrated ☁️",
"main character who chose the peaceful route 🌙",
"if chill was a sport i'd be retired 🏆",
"my brain has too many tabs open",
"professional overthinker, amateur adult",
"not weird, limited edition",
"my life is a meme and i embrace it",
"error 404: cool not found",
"too stubborn to accept defeat",
"if sarcasm burned calories i'd be invisible",
"certified NPC with main character dreams",
"plot twist: i still don't know what's going on",
"running on vibes and poor choices",
"peaked at 7, all downhill",
"allergic to alarm clocks",
"my therapist has homework because of me",
"built different (results pending)",
"professional time waster",
"my attention span left already",
"one braincell, hanging tough",
"tutorial NPC nobody listens to",
"functioning (citation needed)",
"oops i exist",
"was normal once, scary five minutes",
"plan A failed, plan B was fiction",
"i put the fun in dysfunction",
"wifi stronger than my plans",
"chaos coordinator on duty",
"accidentally iconic",
"my autobiography: comedy section",
"bad decisions at record speed",
"competitive napper",
"professionally goofy",
"common sense is my rarest drop 💀",
"i don't have a type, i have a problem",
"google can't help me at this point",
"the only thing i finish is snacks",
"gave up pretending years ago",
"fluent in sarcasm and silence",
"my vibe check returns 'error' every time",
"voted most likely to show up late",
"personality type: controlled chaos",
"my sleep schedule is abstract art",
"minimalist soul, maximalist world 🤍",
"making beauty from ordinary stuff 🌿",
"earth tones and warm hearts 🌿",
"old soul with fresh eyes 🤍",
"poetry in everything 🌿",
"clean lines, clear thoughts 🤍",
"vintage vibes, timeless energy 🤍",
"dark academia vibes, warm heart 🤍",
"painting life in warm tones 🌿",
"journal pages and cafe afternoons 🤍",
"living like a studio ghibli scene 🌿",
"the aesthetic chose me 🤍",
"slow mornings, golden evenings 🌿",
"curated chaos, organized beauty 🤍",
"exhaling masterpieces 🌿",
"dreaming in film grain 🤍",
"every day is a new page 🤍",
"letting colors tell the story 🌿",
"museum heart, gallery brain 🤍",
"quiet beauty of ordinary things 🌿",
"film grain and golden light",
"old books and new ideas 📚",
"analog soul, digital world 🤍",
"aesthetics over everything 🌿",
"curating my life one moment at a time 🤍",
"my feed looks like a mood board 🌿",
"brown paper packages and string 🤍",
"handwriting over typing always ✍️",
"some stories stay untold 🌙",
"the less you know, the better it gets 🖤",
"reading between lines nobody wrote 🌙",
"silence is the loudest statement 🖤",
"enigma encrypted in a username 🌙",
"layers deeper than ocean trenches 🖤",
"answers live inside the questions 🌙",
"a universe behind these eyes 🖤",
"walking a path nobody else sees 🌙",
"thoughts darker than the profile pic 🖤",
"old soul navigating new servers 🌙",
"truth hides where nobody looks 🖤",
"the mystery IS the message 🌙",
"observing everything, saying nothing 🖤",
"depth over surface, always 🌙",
"i am the question mark 🖤",
"fog wrapped soul, crystal clear within 🌙",
"not everyone needs to get it 🖤",
"the night sky keeps my secrets 🌙",
"chapters you'll never read 🖤",
"wandering between seen and unseen 🌙",
"complex thoughts, simple bio 🖤",
"the shadow has layers 🌙",
"born in the in-between 🖤",
"i exist in the spaces between words 🌙",
"the quiet ones notice the most 🖤",
"not mysterious on purpose, just private 🌙",
"my silence has subtitles 🖤",
"stranger things happen in my head 🌙",
"the plot is hidden but it's there 🖤",
"have you eaten? drink water!",
"cozy vibes and open doors",
"your biggest fan even if we just met",
"comfort character irl",
"healing this server one compliment at a time",
"need a friend? i'm here",
"warm hugs and good intentions",
"collecting friends, not enemies",
"empathy is underrated",
"the player who helps new people in the lobby",
"complimenting strangers is my hobby",
"training arc rn dont disturb 💪",
"tower defense is life",
"base defender elite squad",
"just learned a new trick in obby watch this",
"my character died 47 times but whos counting",
"military rp veteran no questions asked",
"speedrunning this game while half asleep",
"swords clash and i stand tall ⚔️",
"building a castle nobody asked for",
"sniper accuracy zero patience 🎯",
"zombie defense expert on weekends",
"racing game enjoyer since birth 🏎️",
"my K/D is a secret for legal reasons",
"farming gems at 4am is normal right",
"sword fights veteran 2017 🗡️",
"king of the hill literally and figuratively",
"loot collector hoarding expert",
"pvp mode engaged permanently",
"stealth gameplay is underrated tbh",
"the one who actually reads the tutorial",
"exploring every corner of the map",
"survival games make me nervous but i love it",
"base raider by night builder by day",
"rocket launcher fan club president 🚀",
"my fortress has traps dont even try",
"blox fruits grinder 24/7",
"cops side or robbers side depends on the mood",
"building mechs in my free time 🤖",
"the random who actually has a plan",
"captain of a team that doesnt exist yet",
"hi",
"bye",
"afk brb",
"probably afk sorry",
"dont read this",
"this bio is a placeholder",
"i need a better bio",
"nothing to see here move along",
"read this u owe me 1 robux",
"average player average bio",
"im here i guess",
"loading personality...",
"404 bio not found",
"insert cool bio here",
"too cool for a bio",
"my other account has a better bio",
"this seemed funnier in my head",
"i wrote this at 3am dont judge",
"its giving no effort",
"this is temporary from 2019",
"spent my robux on something stupid again",
"why is everyone better than me at this game",
"lagging so hard rn its not even funny",
"my wifi cuts out at the worst times",
"forgot why i opened roblox but im here now",
"playing instead of doing what i should be doing",
"i promise ill go outside tomorrow",
"bedtime was 2 hours ago oops",
"this is my 5th account long story",
"traded wrong item crying rn",
"if the servers werent trash id be better",
"im only mean to scammers",
"my screen time report would scare you",
"been procrastinating on roblox since birth basically",
"the ads keep getting me ngl",
"i fall for free robux scams in my nightmares",
"auto clicker and shame 🤷",
"just one more game i keep telling myself",
"is it normal to play this much asking for a friend",
"my teacher plays roblox too i saw her",
"slender = blocked",
"dont offer dont ask dont trade",
"add me or dont idc",
"its not a phase mom said about my roblox phase",
"imagine being a bacon lmao couldnt be me oh wait",
"bobux",
"free bobux in my bio jk thats a scam",
"reporting you in my head rn",
"this server has 2 brain cells and i have both",
"im the last person u wanna trade with trust",
"no im not sharing my private server",
"my pet is cooler than ur pet sorry not sorry",
"whoever stole my limited im watching u 👀",
"the game is rigged and i like it that way",
"no mic gang rise up",
"voice chat is scarier than horror games",
"please stop following me around the map",
"im the random that carries the team somehow",
"kicked from 3 servers today new record 🏆",
"i only play at 3fps its fine",
"rp lover since day one",
"looking for a crew to vibe with",
"dm for rp or dont whatever",
"bloxburg builder at ur service",
"farming simulator life chose me",
"just exploring maps rn",
"favorite game changes weekly",
"base building enjoyer",
"elevator music is my favorite genre",
"collecting badges is my mission in life",
"tycoon grinder no sleep",
"simulator games are my weakness",
"i rate builds for fun dm me",
"mostly afk in my house",
"just here for the free stuff honestly",
"trading is my whole personality now",
"catalog sale is my christmas",
"devex grindset someday maybe",
"i play everything and master nothing",
"murder mystery innocent every round",
"thinking about stuff u wouldnt get",
"life is too short for bad servers",
"we all started as guests once",
"remember when roblox was simple yeah me neither",
"growing up is realizing bacons were the real ones",
"the old roblox lobby hits different in memories",
"nostalgia is just the old oof sound",
"tix era veteran 🎖️",
"been here long enough to see everything change",
"virtual worlds real connections honestly",
"some of my best friends i met on here ngl",
"pixels but the memories are real",
"2017 roblox was a different breed",
"the old death sound was better argue with the wall",
"miss when games were simple and free",
"this game raised me more than school did",
"some of yall werent here for tix and it shows",
"growing up with roblox hits different now",
"joined in 2016 never looked back",
"this game has more lore than my life",
"tower defense games are underrated fight me",
"obby games are harder than they look",
"building > pvp any day",
"fashion shows are competitive and i stand by that",
"horror games on roblox actually slap ngl",
"tycoons are just clicker games with extra steps",
"roleplay or nothing",
"simulator addiction is real and i have it",
"the better your avatar the better you play facts",
"gear fights in 2015 were elite",
"sword fights on the heights veterans stand up",
"jailbreak was the peak of roblox gaming",
"natural disaster survival is still fire after all this time",
"whoever made flee the facility is a genius",
"piggy was the best thing to happen to 2020",
"brookhaven is a lifestyle not a game",
"blox fruits grinders are a different breed fr",
"doors is scarier than actual horror games",
"arsenal sweat and proud of it",
"mm2 knife collection is my flex",
"online after school hit me up",
"weekend warrior only",
"parents said 1 hour but they lost track too",
"eating while playing is a skill",
"homework in one tab roblox in the other",
"summer break = roblox marathon",
"snow day = all day gaming",
"my sibling keeps hogging the computer",
"shared account with my brother hes the weird one",
"logged in from my phone dont judge the avatar",
"mobile player with console dreams",
"touch screen warrior 📱",
"pc master race but playing on laptop",
"playing on chromebook btw",
"30fps and a dream",
"my roblox age is higher than my real age",
"been premium since it was builders club",
"oof",
"roblox > homework and im not even sorry",
"last online 5 minutes ago always",
"someone explain the update to me pls",
"playing the same game for 3 years straight",
"my first roblox account got hacked rip",
"still wearing the free items and vibing",
"catalog is expensive being broke is free",
"ugc creators carry this game fr",
"limited items are just pixels i keep telling myself",
"the oof sound lives in my heart forever",
"remember when guests existed yeah",
"tix removal still hurts ngl",
"my avatar has been the same since 2020 and it works",
"if u trade me im saying nty to everything",
"public servers are chaos and i live for it",
"vip server kid spoiled and grateful",
"been banned from so many servers its a talent",
"the background music in games slaps sometimes",
"my friends list is full of people i forgot",
"level 1 energy level 100 confidence",
"watching youtube tutorials to get good at this game",
"copy pasting this bio bc im lazy",
"mobile players are underrated and i will die on this hill",
"my fps counter is depressing",
"avatar looks different on every device 😭",
"traded my best item for nothing good rip",
"saving up for a face thats just a face",
"the game crashed but my dreams didnt actually they did too",
"why does my character walk so slow fr",
"max friends list zero irl friends nah jk",
"grinding events for free items is my cardio",
"new update broke everything classic",
"remember when the catalog had actual sales 😢",
"joined 2017 never left",
"the adopt me egg economy is confusing",
"roblox premium member and broke irl",
"waiting for the halloween event all year",
"christmas games > everything else",
"this is literally the only game i play",
"my join date is my flex",
"old roblox logo was better dont @ me",
"testing random games at 1am",
"playing games from the front page like a tourist",
"found a hidden game with 2 players its actually fire",
"rating games for fun nobody asked me to",
"the roblox algorithm knows me too well",
"every game is a building game if ur creative enough",
"been here longer than some of these games existed",
"nostalgia trip every time i log in now",
"my old screenshots from 2018 are embarrassing",
"this game has more memories than my camera roll",
"all my friends quit roblox but im still here somehow",
"singleplayer in a multiplayer game mood",
"making friends in random lobbies since forever",
"the last one online in the friend group always",
"2am roblox sessions hit different no cap",
"someone gift me robux pls im begging",
"catalog surfing is my favorite hobby",
"outfit ideas at 3am > sleep",
"roblox raised me and im not ashamed to admit it",
"the game isnt dead yall just grew up",
"classic games deserve more appreciation fr",
"living life in 4/4 time 🎵",
"my playlist IS my personality 🎶",
"music is therapy, rhythm is the prescription 🎵",
"headphones in, world paused 🎶",
"turning feelings into frequencies 🎵",
"every moment deserves a soundtrack 🎶",
"lost in the melody, found in the bass 🎵",
"life without music is just static 🎶",
"concert energy even in the shower 🎵",
"bass drop heartbeat 🎶",
"worlds built from sound 🎵",
"my ears pick up things others miss 🎶",
"if my life had a soundtrack it'd go crazy 🎵",
"vinyl collector, vibe protector 🎶",
"dancing alone in my room is peak life 🎵",
"the lyrics understand me better 🎶",
"lo-fi and late nights 🎵",
"concert dreams and bedroom realities 🎶",
"my brain plays songs that don't exist yet 🎵",
"tune in, the show starts now 🎶",
"every genre, no gatekeeping 🎵",
"aux cord privileges earned not given 🎶",
"singing the wrong lyrics confidently 🎵",
"my queue reveals more than my bio 🎶",
"sound on, world off 🎵",
"reality is overrated, imagination is home 💜",
"swimming against the current since forever 🌊",
"nobody read the rules of this game 💜",
"the edge is where the view is 🌊",
"too real for this scripted world 💜",
"riding the wave of whatever this is 🌊",
"consciousness: gift and curse 💜",
"deep waters, calm surface 🌊",
"breaking patterns that expired 💜",
"the universe gave me lore 🌊",
"normal is an illusion 💜",
"glitch in the matrix and comfortable 🌊",
"wrong timeline but thriving 💜",
"questioning everything is the only exercise 🌊",
"thoughts deeper than the lore 💜",
"comfort zone burned, castle built 🌊",
"the abyss and i are mutual 💜",
"existential adventure > existential crisis 🌊",
"philosophy is my playlist 💜",
"deconstructing reality casually 🌊",
"we live in a simulation and i found the menu 💜",
"reality has bad graphics 🌊",
"my brain argues with itself and both sides lose 💜",
"thinking too much about things that don't exist",
"nothing matters and that's freeing 🌊",
"forest soul, river brain 🌿",
"ocean heart, mountain backbone 🌊",
"trees are better therapists 🌿",
"salt air and sunset prayers 🌊",
"grounded like earth, free like wind 🌿",
"chasing horizons, finding calm 🌊",
"wild soul, steady hands 🌿",
"the rain speaks and i listen 🌊",
"growing like roots, reaching like branches 🌿",
"tidal heart, lunar mind 🌊",
"earth heals what noise breaks 🌿",
"barefoot and present 🌊",
"planted in peace 🌿",
"where the river meets the sea 🌊",
"breathing in nature, breathing out stress 🌿",
"sunrise person pretending to be a night owl 🌊",
"the sky does a lot of the talking for me 🌿",
"happiest outside 🌊",
"mountains over malls every time 🌿",
"rain sounds are my white noise 🌊",
"respawn, retry, refuse to quit",
"skill issue? never heard of that",
"log in, lock in",
"plot armor thicker than my patience",
"stay weird 🌟",
"less is more",
"here before it was cool",
"nah",
"the vibe is the vibe",
"no bio needed",
"offline energy, online presence",
"keep scrolling or say hi 👋",
"this bio intentionally left interesting",
"read this and keep it moving",
"less talk, more everything else",
 ],

 // ─── GROW A GARDEN BIOS (100) ───
 garden: [
"🌱 planted a seed, grew a whole empire 🌱",
"🌻 my garden is louder than your lobby 🌻",
"🌱 growing flowers while they grow drama 🌱",
"🪴 seed by seed, dream by dream 🪴",
"🌿 planted with love, bloomed with patience 🌿",
"🌱 watch me grow from nothing to legendary 🌱",
"🪴 started as a sprout, now i'm the whole garden 🪴",
"🌱 every seed i plant turns to gold 🌱",
"🌻 growing stronger while others sleep 🌻",
"🪴 watered by kindness, fed by sunshine 🪴",
"🌱 don't rush it, the best gardens take time 🌱",
"🌿 planting good vibes, harvesting greatness 🌿",
"🌱 my growth is silent but the results are loud 🌱",
"🪴 one seed at a time, one bloom at a time 🪴",
"🌱 roots deep, petals bright, soul unstoppable 🌱",
"🌻 growing in every season, even the hard ones 🌻",
"🪴 the soil knows my story better than anyone 🪴",
"🌱 i don't just grow, i flourish 🌱",
"🌿 seeds of today, forests of tomorrow 🌿",
"🌱 watch the garden, not the gardener 🌱",
"🌸 my flowers bloom brighter than your avatar 🌸",
"🌷 flower queen of the whole server 🌷",
"🌺 pretty petals, powerful roots 🌺",
"🌸 born to bloom, made to shine 🌸",
"🌷 picking flowers and picking wins 🌷",
"🌼 sunflower soul in a dandelion world 🌼",
"🌸 she blooms where she is planted 🌸",
"🌺 flower girl energy running through my veins 🌺",
"🌷 i grow roses where others see dirt 🌷",
"🌸 my garden has zero weeds and infinite vibes 🌸",
"🌼 golden petals and a diamond heart 🌼",
"🌺 the rarest flower in every garden 🌺",
"🌸 soft petals, sharp thorns, sweet vibes 🌸",
"🌷 flowers in my hair, sunshine in my soul 🌷",
"🌼 bloom so hard the whole server notices 🌼",
"🌸 petal by petal, i built something beautiful 🌸",
"🌺 wildflower energy, can't be tamed 🌺",
"🌷 i smell like fresh roses and victory 🌷",
"🌼 flower power is the only power i need 🌼",
"🌸 my bouquet is bigger than your flex 🌸",
"🧑‍🌾 farm life chose me and i said yes 🧑‍🌾",
"🌾 harvest king, crop legend, garden boss 🌾",
"🧑‍🌾 dirty hands, clean heart, full harvest 🧑‍🌾",
"🌾 reap what you sow and i sowed greatness 🌾",
"🍃 leaf by leaf, i'm building a paradise 🍃",
"🧑‍🌾 watering my plants and my dreams daily 🧑‍🌾",
"🌾 golden harvest, golden soul 🌾",
"🍃 the harvest is always worth the wait 🍃",
"🧑‍🌾 farmer by day, legend by night 🧑‍🌾",
"🌾 my crops never fail because i never quit 🌾",
"🍃 growing veggies and growing as a person 🍃",
"🧑‍🌾 garden grinder, no days off from planting 🧑‍🌾",
"🌾 sow kindness, harvest love 🌾",
"🍃 my farm is my kingdom and i rule it well 🍃",
"🧑‍🌾 hands in the soil, heart in the clouds 🧑‍🌾",
"🌾 the farmer with the freshest crops in the server 🌾",
"🍃 touch grass? i GROW grass 🍃",
"🧑‍🌾 planting seeds of chaos and flowers of peace 🧑‍🌾",
"🌾 from tiny seed to towering tree, that's me 🌾",
"🍃 harvest season is my season 🍃",
"🌿 garden fairy with main character energy 🌿",
"🪻 lavender dreams and morning dew 🪻",
"🌿 nature heals what drama steals 🌿",
"🪴 cottagecore gardener in a digital world 🪴",
"🌿 touching grass professionally since day one 🌿",
"🍀 lucky clover collector, blessed gardener 🍀",
"🪻 secret garden, secret power 🪻",
"🌿 green thumb, golden heart 🌿",
"🪴 my aesthetic is dirt, dewdrops, and daisies 🪴",
"🍀 four-leaf clover luck running through my garden 🍀",
"🌿 botanical soul, poetic blooms 🌿",
"🪻 living my garden fantasy one flower at a time 🪻",
"🌿 mother nature's favorite player 🌿",
"🪴 peaceful garden, peaceful mind 🪴",
"🍀 blooming in silence, growing in peace 🍀",
"🌿 the garden whispers and i listen 🌿",
"🪻 enchanted garden vibes only 🪻",
"🌿 rooted in love, branching into greatness 🌿",
"🪴 my plants have a better life than most people 🪴",
"🍀 green is not just a color, it's a lifestyle 🍀",
"🌱 my garden flex is unmatched, don't even try 🌱",
"🐝 busy bee in the best garden on the server 🐝",
"🌱 level 99 gardener, level 1 at everything else 🌱",
"🦋 butterflies come to MY garden first 🦋",
"🌱 garden so good, even the weeds are jealous 🌱",
"🐝 pollinating the server with good energy 🐝",
"🌱 if growing was a sport, i'd be the MVP 🌱",
"🦋 butterfly garden queen, no one comes close 🦋",
"🌱 speedrunning the garden grind 🌱",
"🐝 honey money from my garden empire 🐝",
"🌱 you grow flowers, i grow legends 🌱",
"🦋 my garden attracts all the rare butterflies 🦋",
"🌱 pro gardener, casual human being 🌱",
"🐝 the bees chose my garden because it's the best 🐝",
"🌱 garden battle? i already won 🌱",
"🦋 planting, growing, flexing, repeat 🦋",
"🌱 they said touch grass, so i grew an entire field 🌱",
"🐝 sweet like honey, sharp like thorns 🐝",
"🌱 welcome to my garden, no toxics allowed 🌱",
"🦋 grow a garden? i grew a whole forest 🦋",
 ]
};
